# -*- coding: utf-8 -*-
"""11plot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SkCLmkzE7gWpNHq52TyYjgF7nVHqw-vL
"""

###chart전처리
from datetime import datetime, timedelta
import pandas as pd
import numpy as np

#datetime
pos_date = [i.split('T', 1)[0] for i in pos_date_list]
pos_date = pd.to_datetime(pos_date, format='%Y-%m-%d')
pos_date_data = pd.DataFrame({'datetime':pos_date})
neu_date = [i.split('T', 1)[0] for i in neu_date_list]
neu_date = pd.to_datetime(neu_date, format='%Y-%m-%d')
neu_date_data = pd.DataFrame({'datetime':neu_date})
neg_date = [i.split('T', 1)[0] for i in neg_date_list]
neg_date = pd.to_datetime(neg_date, format='%Y-%m-%d')
neg_date_data = pd.DataFrame({'datetime':neg_date})

neg = neg_date_data['datetime'].dt.to_period('m').value_counts()
neu = neu_date_data['datetime'].dt.to_period('m').value_counts()
pos = pos_date_data['datetime'].dt.to_period('m').value_counts()
df = pd.concat([neg, neu, pos], axis=1, keys=('negative','neutral','positive'))
print (df)
#df.plot()
df.plot.bar(stacked=True)

###
import csv
data_path = 'cctvdata.csv'

datalist = []
datadict = {}
with open(data_path, 'r', encoding='euc-kr') as data_file:
  reader = csv.reader(data_file)
  for row in reader:
    row[6] = row[6].replace('01', '02')
    datadict[row[6]] = row[6]
  print(datadict)

###
from datetime import datetime, timedelta
import pandas as pd

df = pd.read_csv('cctvdata.csv', 'r', encoding='euc-kr', skiprows=[0,1,2,3])

###11.3이거
import pandas as pd #csv
import matplotlib.pyplot as plt

df = pd.read_csv('cctv1.csv', 'r', encoding='euc-kr')
#print(df)

def scatter_plot():
  reader = pd.read_csv('cctv1.csv', encoding='euc-kr') 
  toshow = reader.loc[:, 'no':'AM06PM12'] #combine()

  fig, ax = plt.subplots()

  ax.scatter(toshow['AM00AM06'], toshow['AM06PM12'])#label:str

  plt.xlabel('day')
  plt.ylabel('night')
  
  ax.grid(True)

  plt.show()  

  #구간 정하고 이름 출력
  for x, y, name in zip(toshow['AM00AM06'], toshow['AM06PM12'], toshow['carmera_name']):
    if x > 600000 and y > 600000:
      print(name, x, y)

scatter_plot()

###11.3test
import pandas as pd #csv
import matplotlib.pyplot as plt

df = pd.read_csv('cctv1.csv', 'r', encoding='euc-kr')
#print(df)

def scatter_plot():
  reader = pd.read_csv('cctv1.csv', encoding='euc-kr') 
  toshow = reader.loc[:, 'no':'AM06PM12'] #combine()

  fig, ax = plt.subplots()

  ax.scatter(toshow['AM00AM06'], toshow['AM06PM12'])#label:str

  plt.xlabel('day')
  plt.ylabel('night')
  #ax.legend(toshow['carmera_name'])
  ax.grid(True)
  #x_text = toshow['carmera_name']
  #y_text = toshow['carmera_name']
  #ax.text(x_text,y_text,s=12)
  #enumerate(toshow['AM00AM06'], toshow['AM06PM12'])
  #enumerate(zip(toshow['AM00AM06'], toshow['AM06PM12']))
  for txt in toshow['carmera_name']:
    for x, y in zip(toshow['AM00AM06'], toshow['AM06PM12']):
      ax.annotate(txt, (x,y))
  plt.show()

scatter_plot()

'''
textstr
The text of the annotation. s is a deprecated synonym for this parameter.

xy(float, float)
The point (x, y) to annotate. The coordinate system is determined by xycoords.
'''
###7.3unuse
import pandas as pd #csv
import matplotlib.pyplot as plt

df = pd.read_csv('cctv1.csv', 'r', encoding='euc-kr')
#print(df)

def scatter_plot():
  reader = pd.read_csv('cctv1.csv', encoding='euc-kr') 
  toshow = reader.loc[:, 'no':'AM06PM12'] #combine()

  fig, ax = plt.subplots()

  ax.scatter(toshow['AM00AM06'], toshow['AM06PM12'])#label:str

  plt.xlabel('day')
  plt.ylabel('night')
  #ax.legend(toshow['carmera_name'])
  ax.grid(True)
  #x_text = toshow['carmera_name']
  #y_text = toshow['carmera_name']
  #ax.text(x_text,y_text,s=12)
  #enumerate(toshow['AM00AM06'], toshow['AM06PM12'])
  for txt in toshow['carmera_name']:
    for x, y in zip(toshow['AM00AM06'], toshow['AM06PM12']):
      ax.annotate(txt, (x,y))
  plt.show()
  
scatter_plot()

###11.3
import pandas as pd #csv
import matplotlib.pyplot as plt

df = pd.read_csv('cctv1.csv', 'r', encoding='euc-kr')
#print(df)

def scatter_plot():
  reader = pd.read_csv('cctv1.csv', encoding='euc-kr') 
  toshow = reader.loc[:, 'no':'AM06PM12'] #combine()

  fig, ax = plt.subplots()
  for color in toshow['carmera_name']:
    ax.scatter(toshow['AM00AM06'], toshow['AM06PM12'], label=color,
               alpha=0.3, edgecolors='none')

  ax.legend()
  ax.grid(True)

  plt.show()
  
#scatter_plot()

###11.4이거
import pandas as pd #csv
import matplotlib.pyplot as plt

df = pd.read_csv('cctv2.csv', 'r', encoding='euc-kr')
#print(df)

def scatter_plot2():
  reader = pd.read_csv('cctv2.csv', encoding='euc-kr') 
  df = reader.loc[:, 'no':'police_force']

  size = df['police_force']
  s = [s//10 for s in size]

  plt.scatter(df['lamp'], df['buildings'],  s=s, color="blue", alpha=0.5)

  plt.xlabel('lamp')
  plt.ylabel('buildings')
  plt.show()
  
scatter_plot2()

'''
  s = [3*s**2 for s in size]
  fig, ax = plt.subplots(figsize=(10, 6))
  ax.scatter(x = df['lamp'], y = df['buildings'], s=s) #markersize
'''

##11.4test
import pandas as pd #csv
import matplotlib.pyplot as plt

df = pd.read_csv('cctv2.csv', 'r', encoding='euc-kr')
#print(df)

def scatter_plot2():
  reader = pd.read_csv('cctv2.csv', encoding='euc-kr') 
  df = reader.loc[:, 'no':'police_force']

  size = df['police_force']
  s = [s//10 for s in size]

  fig, ax = plt.subplots()

  ax.scatter(df['lamp'], df['buildings'],  s=s, color="blue", alpha=0.5)

  plt.xlabel('lamp')
  plt.ylabel('buildings')

  for txt in df['police_force']:
    for x, y in zip(df['lamp'], df['buildings']):
      ax.annotate(txt, (x,y))
  plt.show()
  
scatter_plot2()

###
from datetime import datetime, timedelta
import pandas as pd

day_date = [i.split('|', 1)[0] for i in datalist]
day_date = pd.to_datetime(day_date, format='%Y%m%d', errors='ignore')
day_date_data = pd.DataFrame({'datetime':day_date})
#day = day_date_data['datetime'].dt.to_period('M').value_counts()
night_date = [i.split('|', 1)[0] for i in datalist]
night_date = pd.to_datetime(night_date, format='%Y%m%d', errors='ignore')
night_date_data = pd.DataFrame({'datetime':night_date})
#day = day_date_data['datetime'].dt.to_period('M').value_counts()

df = pd.concat([ ], axis=1. keys=(''))
print(df)
df.plot.scatter(scattered=True)

#11.2이거
import pandas as pd #csv
import matplotlib.pyplot as plt

df = pd.read_csv('crime.csv', 'r', encoding='euc-kr')
#print(df)

def histplot():
  reader = pd.read_csv('crime.csv', encoding='euc-kr') 

  df1 = reader.loc[:,['Robebery']]
  df2 = reader.loc[:,['Burglary']]
  df3 = reader.loc[:,['Fraud']]
  df4 = reader.loc[:,['Terror']]
  df5 = reader.loc[:,['Assault']]
  idx = reader.loc[:,['year']]

  df = pd.concat([df1, df2, df3, df4, df5], axis=1)

  #df.plot()
  plt.plot(idx, df)

  plt.xlabel('year')
  plt.ylabel('crime occured')
  #label

  plt.grid()
  plt.legend(['Robebery','Burglary','Fraud','Terror','Assault'])

  plt.show()

histplot()

'''
plt.figure(figsize=(4, 10))
plt.plot(x, parabola)
plt.savefig('crimeplot2.png')
'''

import pandas as pd #csv
import matplotlib.pyplot as plt

df = pd.read_csv('crime.csv', 'r', encoding='euc-kr')
#print(df)

def histplot():
  reader = pd.read_csv('crime.csv', encoding='euc-kr') 
  
  idx = reader.loc[:,['year']]

  df1 = reader.loc[:,['crime1']]
  df2 = reader.loc[:,['crime2']]
  df3 = reader.loc[:,['crime3']]
  df4 = reader.loc[:,['crime4']]
  df5 = reader.loc[:,['crime5']]

  df = pd.concat([idx, df1, df2, df3, df4, df5], axis=0)
  df.set_index('year', inplace=True)
  print(df.head())

  fig, ax = plt.subplots()

  ax.plot(df)

  plt.xlabel('year')
  plt.ylabel('crime occured')
  #text

  plt.show()

histplot()

import pandas as pd #csv
import matplotlib.pyplot as plt

df = pd.read_csv('crime.csv', 'r', encoding='euc-kr')
#print(df)

def histplot():
  reader = pd.read_csv('crime.csv', encoding='euc-kr') 

  df1 = reader.loc[:,['crime1']]
  df2 = reader.loc[:,['crime2']]
  df3 = reader.loc[:,['crime3']]
  df4 = reader.loc[:,['crime4']]
  df5 = reader.loc[:,['crime5']]

  df = pd.concat([df1, df2, df3, df4, df5], axis=0)

  df.plot()

  plt.xlabel('year')
  plt.ylabel('crime occured')
  #text / annotation

  plt.show()

histplot()

import pandas as pd #csv
import matplotlib.pyplot as plt

df = pd.read_csv('crime.csv', 'r', encoding='euc-kr')
#print(df)

def histplot():
  reader = pd.read_csv('crime.csv', encoding='euc-kr') 
  
  df1 = reader.loc[:,['year','crime1']]
  df2 = reader.loc[:,['year','crime2']]
  df3 = reader.loc[:,['year','crime3']]
  df4 = reader.loc[:,['year','crime4']]
  df5 = reader.loc[:,['year','crime5']]

  plt.hist(df1['year'],density=True, alpha=0.5, histtype='step')
  plt.hist(df2['year'],density=True, alpha=0.5, histtype='step')
  plt.hist(df3['year'],density=True, alpha=0.5, histtype='step')
  plt.hist(df4['year'],density=True, alpha=0.5, histtype='step')
  plt.hist(df5['year'],density=True, alpha=0.5, histtype='step')

  plt.legend(['1','2','3','4','5'])

  plt.xlabel('year')
  plt.ylabel('crime occured')
  #text / annotation

  plt.show()

histplot()

###11.4
import pandas as pd #csv
import matplotlib.pyplot as plt

def scatter_plot3():
  reader = pd.read_csv('spotcover.csv', encoding='euc-kr') 
  df = reader.loc[:, 'district_name':'cover']

  size = df['cover']

  fig, ax = plt.subplots()

  ax.scatter(df['x'], df['y'],  s=size, color="green", alpha=0.5)

  ax.grid(True)

  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  
scatter_plot3()

'''
  s = [3*s**2 for s in size]
  fig, ax = plt.subplots(figsize=(10, 6))
  ax.scatter(x = df['lamp'], y = df['buildings'], s=s) #markersize
'''