# -*- coding: utf-8 -*-
"""9-4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jMCMG-xpSl0uLENANbLJ0musAsyRQmsE
"""

class sample:
    def __init__(self, name, collection_time, inspection_time):
        self.name = name
        self.collection_time = collection_time
        self.inspection_time = inspection_time

import random
random.seed(66)

namelist = ['John.W','Judith.G','Brett.N.O','Tracy.H.N','Michael.B','Melissa.R','Andrea.F','Thomas.W.J','Veronica.C','Blake.W','Darren.V','Scott.C','Bill.R.C','Jeffrey.S','Dwayne.C','Bruce.F','Sara.P','Stromy.U.J','Lala.P.V','Maddox.B']
collection_time = [205503180530, 205503180613, 205503180733, 205503180814, 205503180945, 205503181242, 205503181256, 205503181581, 205503181600, 205503181621, 205503181641, 205503181747, 205503181728, 205503181729, 205503181823, 205503181902, 205503191125, 205503191325, 205503191400, 205503191505]
inspection_time = [205503200901, 205503201014, 205503200312, 205503200611, 205503200212, 205503200632, 205503200239, 205503200017, 205503200420, 205503200311, 205503200538, 205503200018, 205503200603, 205503200131, 205503200021, 205503200135, 205503200011,205503200511,205503200411,205503200451] 
random.shuffle(inspection_time)

#mission1
tosort = []
for i in range(len(namelist)):
  tosort.append(sample(namelist[i], collection_time[i],inspection_time[i]))

def selection_sort(sort_temp):
    swap = 0
    tosort=sort_temp[:]
    for i in range(len(tosort) - 1):
        min_idx = i
        for j in range(i + 1, len(tosort)):
            if tosort[j].inspection_time < tosort[min_idx].inspection_time:
                min_idx = j
        tosort[i], tosort[min_idx] = tosort[min_idx], tosort[i]
        swap += 1
        print("%3d"%(swap), end=' ')
        for i in tosort:
          print("%20s"%(i.name), end=' ')
        print('\n')
        
selection_sort(tosort)
'''
        if swap == 12 :
            return tosort[12].name

print(selection_sort(tosort))
'''


#q: 12, 13
#a: Bil.R.C

class sample:
    def __init__(self, name, datetime, item):
        self.name = name
        self.datetime = datetime
        self.item = item

import random
random.seed(66)

namelist = ['John.W','Andrea.F','Veronica.C','Judith.G','Brett.O','Bil.R.C','Scott.C','Bruce.F','Darren.V','Melissa.R','Thomas.W','Michael.B','Tracy.N','Jeffrey.S','Dwayne.C','Blake.W','Sara.P',]
wordlist = ['AFG','AGBM','WXT','WET','YUZ','AXZB','ER','INM','HJA','SSQ','LKZ','EMZ','HS','WBC','LXE','LRU','FIFO']

tosort = []
for i in range(len(namelist)):
  tosort.append(sample(namelist[i], random.randint(205503200001,205503200801),wordlist[i]))

def selection_sort(lista_temp):
    swap = 0
    lista=lista_temp[:]
    for i in range(len(lista) - 1):
        min_idx = i
        for j in range(i + 1, len(lista)):
            if lista[j].datetime < lista[min_idx].datetime:
                min_idx = j
        lista[i], lista[min_idx] = lista[min_idx], lista[i]
        swap += 1
        print("%3d"%(swap), end=' ')
        for i in lista:
          print("%20s"%(i.name), end=' ')
        print()

selection_sort(tosort)